import react from 'react';
import Head from 'next/head';
import { NextPage } from 'next/types';
import { Button, Typography } from 'antd';
import { OAUTH_URL } from '@/utils/getNextConfig';

const { Link } = Typography;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={OAUTH_URL}>登录</Link>
    </div>
  );
};

export default Home;
