import react from 'react';
import Head from 'next/head';
import Image from 'next/image';
import { NextPage } from 'next/types';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      是多少
    </div>
  );
};

export default Home;
