import react from 'react';
import Head from 'next/head';
import { NextPage } from 'next/types';
import { Button } from 'antd';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>123</Button>
      <div>gitub HomePage</div>
    </div>
  );
};

export default Home;
